version: "3"

services:

  database:
    image: mariadb
    container_name: database
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
    ports: 
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
