version: "3"

services:

  db:
    image: mariadb
    restart: always
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
    healthcheck:
        test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
        start_period: 1m
        start_interval: 10s
        interval: 1m
        timeout: 5s
        retries: 3

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
